# Specify the providers
providers = ["elixir"]

# Setup phase: Include Node.js and Git alongside Elixir/Erlang
[phases.setup]
nixPkgs = ["elixir", "erlang", "nodejs", "git"]

# Build phase: Run the necessary commands
[phases.build]
# cmds = [
#   "mix local.hex --force",
#   "mix local.rebar --force",
#   "mix deps.get --only prod",  # This will respect mix.lock
#   "mix deps.compile",
#   "mix compile",
#   "cd assets && npm install",  # Install Node.js dependencies
#   "cd assets && npm run build",
#   "cd assets && npm run build-server",  # Explicitly run the server build
#   "npm install @vue/runtime-dom @vue/server-renderer vue",  # Install Vue packages for SSR
#   "mix phx.digest",  # Instead of mix assets.deploy to avoid running build-server twice
#   "mix assets.deploy"
# ]

cmds = [
  "mix local.hex --force",
  "mix local.rebar --force",
  "mix deps.get --only prod",
  "mix setup",
  "npm install @vue/runtime-dom @vue/server-renderer vue primevue",  # Install Vue packages for SSR
  "mix assets.deploy"
]

# Start phase
[start]
cmd = "mix phx.server"